"use client";

import { createSlice, PayloadAction } from "@reduxjs/toolkit";

/* -------------------------------------------------------------------
🎯 Todo Type Definition
------------------------------------------------------------------- */
export interface Todo {
  id: string;           // Unique ID (generated by nanoid)
  title: string;        // Todo title (short headline)
  description: string;  // Detailed description
  date: string;         // Due date (YYYY-MM-DD)
  time: string;         // Time (HH:mm)
  completed: boolean;   // Completion status
}

/* -------------------------------------------------------------------
📦 Slice State Definition
------------------------------------------------------------------- */
interface TodoState {
  todos: Todo[];
}

/* -------------------------------------------------------------------
💾 Load saved todos from localStorage if available
------------------------------------------------------------------- */
const savedTodos =
  typeof window !== "undefined" ? localStorage.getItem("todos") : null;

const initialState: TodoState = {
  todos: savedTodos ? JSON.parse(savedTodos) : [],
};

/* -------------------------------------------------------------------
🧩 Create Redux Slice
------------------------------------------------------------------- */
const todoSlice = createSlice({
  name: "todos",
  initialState,
  reducers: {
    // ➕ Add new todo
    addTodo: (state, action: PayloadAction<Todo>) => {
      state.todos.unshift(action.payload); // Add new todo to the top
      localStorage.setItem("todos", JSON.stringify(state.todos)); // Persist
    },

    // 🔄 Toggle completion status
    toggleTodo: (state, action: PayloadAction<string>) => {
      const todo = state.todos.find((t) => t.id === action.payload);
      if (todo) todo.completed = !todo.completed;
      localStorage.setItem("todos", JSON.stringify(state.todos));
    },

    // ❌ Delete a todo by ID
    deleteTodo: (state, action: PayloadAction<string>) => {
      state.todos = state.todos.filter((t) => t.id !== action.payload);
      localStorage.setItem("todos", JSON.stringify(state.todos));
    },

    // ✏️ Update an existing todo (used for edit modal)
    updateTodo: (state, action: PayloadAction<Todo>) => {
      const index = state.todos.findIndex((t) => t.id === action.payload.id);
      if (index !== -1) {
        state.todos[index] = action.payload;
      }
      localStorage.setItem("todos", JSON.stringify(state.todos));
    },

    // 🧹 Clear all completed todos
    clearCompleted: (state) => {
      state.todos = state.todos.filter((t) => !t.completed);
      localStorage.setItem("todos", JSON.stringify(state.todos));
    },
  },
});

/* -------------------------------------------------------------------
📤 Export Actions & Reducer
------------------------------------------------------------------- */
export const {
  addTodo,
  toggleTodo,
  deleteTodo,
  updateTodo,
  clearCompleted,
} = todoSlice.actions;

export default todoSlice.reducer;
